import Link from "next/link";
import { SiteFooter, SiteNav } from "../components/SiteNav";

export default function Ecosystem() { return <><SiteNav/><main className="inner-page ecosystem-page">
  <section className="inner-hero"><div className="v2-kicker">B2B2SME COMMERCIAL MODEL</div><h1>Keep starting free.<br/><em>Charge for progress at scale.</em></h1><p>ESG Starter is designed to remove the first barrier for SMEs and NGOs, then earn revenue from guided implementation and organisations funding a portfolio of participants.</p></section>
  <section className="model-grid"><article><span>FREE START</span><h2>Begin without fear</h2><p>One organisation can complete a practical ESG readiness check, receive a starter action plan and create one basic impact record without needing a sales call.</p><ul><li>Readiness assessment</li><li>Starter action plan</li><li>One basic impact record</li></ul></article><article className="featured"><span>GUIDED ORGANISATION</span><h2>Pay for continuity</h2><p>SMEs pay when they need ongoing evidence management, multi-site visibility, monthly check-ins, guided onboarding and report-ready output.</p><ul><li>Evidence workspace</li><li>Multi-site tracking</li><li>Guided implementation</li></ul></article><article><span>SPONSORED COHORT</span><h2>Scale through partners</h2><p>Banks, corporates, associations and foundations fund a group of SMEs, suppliers or NGOs to participate and receive aggregated cohort progress.</p><ul><li>Partner-funded access</li><li>Cohort progress view</li><li>Shared impact summary</li></ul></article></section>
  <section className="partner-roles"><div><div className="v2-kicker">WHO HELPS SCALE IT</div><h2>One beneficiary.<br/>Multiple value creators.</h2></div><div><article><b>Banks & funders</b><p>Help SMEs organise evidence for more informed sustainability and financing conversations.</p></article><article><b>Accounting firms</b><p>Offer implementation support without building a separate ESG data system for every client.</p></article><article><b>Corporates & foundations</b><p>Support suppliers, community partners and CSR programmes with a consistent impact record.</p></article><article><b>Associations</b><p>Give member SMEs a realistic starting pathway rather than a one-off awareness session.</p></article></div></section>
  <section className="proposal-score"><div><div className="v2-kicker">HOW WE WILL TEST PRICING</div><h2>Validate willingness to pay, not assumptions.</h2></div><div className="score-grid"><div><b>Free</b><span>Test whether assessment converts to completed action plans.</span></div><div><b>Guided</b><span>Test an annual organisation package with onboarding and a first report.</span></div><div><b>Cohort</b><span>Test a sponsored 90-day programme for a group of organisations.</span></div><div><b>Partner</b><span>Test whether portfolio insights create value for the funding organisation.</span></div></div><p className="proposal-note">Pricing is intentionally not fixed before pilot validation. ESG Starter will test packages, usage and partner value with early adopters.</p></section>
  <section className="v2-final"><div><div className="v2-kicker">PARTNER WITH ESG STARTER</div><h2>Make more good work visible.</h2></div><div><p>We are looking for early ecosystem partners who want to test a practical ESG starting method with real organisations.</p><Link className="v2-button primary" href="/contact">Start a conversation <b>↗</b></Link></div></section>
</main><SiteFooter/></>; }
