import Link from "next/link";
import { SiteFooter, SiteNav } from "../components/SiteNav";

export default function CyberjayaPilot() { return <><SiteNav/><main className="inner-page proposal-page">
  <section className="proposal-hero"><div><div className="v2-kicker">CYBERJAYA LIVING LAB PROPOSAL</div><h1>A practical ESG testbed for the organisations that keep a city moving.</h1><p>ESG Starter proposes a 90-day, founder-led discovery pilot for Cyberjaya SMEs, NGOs and community-facing organisations that need a simple way to turn everyday action into credible ESG evidence.</p><div className="proposal-actions"><Link className="v2-button primary" href="/pilot-workspace">Try the prototype <b>↗</b></Link><Link className="v2-button ghost" href="/contact">Register pilot interest <b>→</b></Link></div></div><aside><span>PROPOSED PILOT</span><b>5–10</b><p>Cyberjaya organisations to be recruited with ecosystem support.</p><div><i>90</i><span>days to test, learn and refine</span></div><div><i>01</i><span>shared ESG data-to-report workflow</span></div></aside></section>
  <section className="proposal-section"><div className="proposal-heading"><div className="v2-kicker">WHAT WILL BE TESTED</div><h2>Not a workshop.<br/><em>A measurable product pilot.</em></h2></div><div className="proposal-test-grid"><article><i>01</i><h3>Start</h3><p>Can an organisation complete a sector-aware ESG baseline without an ESG department or consultant-led spreadsheet exercise?</p></article><article><i>02</i><h3>Collect</h3><p>Can teams submit a small set of monthly data points and attach the evidence they already hold?</p></article><article><i>03</i><h3>Act</h3><p>Does a visible action plan help teams understand their next practical ESG step?</p></article><article><i>04</i><h3>Report</h3><p>Can one structured data set create a useful baseline report for partner, CSR and funding conversations?</p></article></div></section>
  <section className="proposal-timeline"><div className="v2-kicker">90-DAY DESIGN</div><div className="timeline-grid"><article><span>Weeks 1–2</span><h3>Recruit & configure</h3><p>Select pilot organisations, assign one data owner each and configure education, services, NGO or SME starter templates.</p></article><article><span>Weeks 3–6</span><h3>Baseline & evidence</h3><p>Complete the baseline, capture existing bills, policies, activity records and evidence of current practices.</p></article><article><span>Weeks 7–10</span><h3>Monthly rhythm</h3><p>Test a low-effort monthly check-in, missing-data reminders and practical action ownership.</p></article><article><span>Weeks 11–12</span><h3>Report & learn</h3><p>Generate pilot summaries, collect user feedback and decide what must improve before commercial rollout.</p></article></div></section>
  <section className="proposal-score"><div><div className="v2-kicker">SUCCESS METRICS</div><h2>What success looks like.</h2></div><div className="score-grid"><div><b>70%</b><span>of recruited organisations complete a baseline</span></div><div><b>60%</b><span>submit at least one monthly check-in</span></div><div><b>&lt;30 min</b><span>target time for a first baseline assessment</span></div><div><b>1 report</b><span>generated per active pilot organisation</span></div></div><p className="proposal-note">These are pilot targets, not claimed outcomes. No Cyberjaya organisation has been confirmed on this website yet.</p></section>
  <section className="proposal-ask"><div><div className="v2-kicker">WHAT ESG STARTER NEEDS</div><h2>Access to a real testbed, not a logo wall.</h2></div><p>We are seeking introductions to suitable Cyberjaya SMEs, NGOs and community organisations; feedback from ecosystem mentors; and a practical setting to test adoption, data quality and report usefulness. Interested organisations can begin with a non-binding pilot discussion.</p><Link className="v2-button primary" href="/contact">Discuss pilot participation <b>↗</b></Link></section>
</main><SiteFooter/></>; }
