import Link from "next/link";
import { SiteFooter, SiteNav } from "../components/SiteNav";

const centres = [
  { name: "Bukit Jalil", students: 76, staff: 3, electricity: 683, water: 46, status: "Ready" },
  { name: "Cheras Balakong", students: 62, staff: 3, electricity: 536, water: 39, status: "Ready" },
  { name: "Puchong Jaya", students: 69, staff: 3, electricity: 558, water: 42, status: "In review" },
];

export default function KindlePilot() { return <><SiteNav /><main className="km-page">
  <section className="km-hero"><div><div className="km-eyebrow">Founder-led pilot / selected Klang Valley centres</div><h1>Make the work<br />already happening <span>visible.</span></h1><p>ESG Starter helps a multi-centre education network establish an ESG baseline, organise evidence and see the next practical actions.</p><Link className="v2-button primary" href="/pilot-workspace">Open interactive prototype <b>↗</b></Link></div><div className="km-hero-media"><img src="/kindle-pilot-hero.png" alt="Education professionals reviewing learning and impact information together" /><aside className="km-demo-note"><b>Pilot configuration</b><p>Three selected centres are preparing their baseline. Utility values will move from planning figures to verified monthly records as bills are collected.</p></aside></div></section>
  <section className="km-dashboard"><div className="km-dashboard-top"><div><div className="km-caption">KINDLE MIND / ESG STARTER BASELINE</div><h2>Quarterly pilot overview</h2><p>Selected Klang Valley learning centres · Q3 2026</p></div><span className="km-chip">● Pilot baseline</span></div><div className="km-kpis"><div><span>Data completion</span><strong>72<small>%</small></strong><i><b style={{width:"72%"}} /></i><em>Baseline in progress</em></div><div><span>Students reached</span><strong>207</strong><em>Across 3 pilot centres</em></div><div><span>Teacher training</span><strong>36<small> hrs</small></strong><em>Teaching & learning practice</em></div><div><span>Evidence items</span><strong>24</strong><em>Records, photos & documents</em></div></div><div className="km-grid"><article className="km-card km-progress"><div className="km-card-head"><div><span>ESG READINESS</span><h3>From baseline to action</h3></div><b>72%</b></div><div className="km-ring"><div>72<small>%</small><span>complete</span></div></div><ul><li><i className="green" />Environment baseline <b>70%</b></li><li><i className="blue" />Social impact evidence <b>82%</b></li><li><i className="gold" />Governance foundation <b>64%</b></li></ul></article><article className="km-card km-plan"><div className="km-card-head"><div><span>90-DAY ACTION PLAN</span><h3>Priority next steps</h3></div><a href="#report">View report →</a></div><div className="km-task done"><i>✓</i><div><b>Collect three months of utility bills</b><span>Centre utility baseline</span></div><em>In progress</em></div><div className="km-task"><i>2</i><div><b>Assign a centre data owner</b><span>Principal accountable; teacher assists</span></div><em>Next</em></div><div className="km-task"><i>3</i><div><b>Start simple monthly ESG check-in</b><span>Five-minute, ten-field form</span></div><em>Next</em></div><div className="km-task"><i>4</i><div><b>Document parent & child safeguarding SOP</b><span>Governance baseline</span></div><em>Planned</em></div></article></div></section>
  <section className="km-centres"><div className="km-section-title"><div><span>PILOT CENTRES</span><h2>A shared structure,<br /><em>centre-level visibility.</em></h2></div><p>Each centre submits only the information it can realistically provide. The dashboard keeps the network view clear without turning teachers into ESG administrators.</p></div><div className="km-table"><div className="km-row km-table-head"><span>Centre</span><span>Students</span><span>Team</span><span>Electricity*</span><span>Water*</span><span>Readiness</span></div>{centres.map((c) => <div className="km-row" key={c.name}><b>{c.name}</b><span>{c.students}</span><span>{c.staff}</span><span>{c.electricity} kWh</span><span>RM {c.water}</span><em className={c.status === "Ready" ? "ready" : "review"}>{c.status}</em></div>)}<div className="km-table-note">*Utility figures are provisional planning values. Verified electricity and water information will replace them as monthly centre bills are collected.</div></div></section>
  <section className="km-esg" id="report"><div className="km-section-title"><div><span>ESG BASELINE REPORT</span><h2>What Kindle Mind is<br /><em>already doing.</em></h2></div><p>The first report does not pretend the organisation is perfect. It makes existing action visible, identifies data gaps and turns them into a realistic plan.</p></div><div className="km-pillars"><article><div className="km-pillar-icon env">E</div><h3>Environment</h3><p>Digital accounting, reusable teaching materials and reused delivery boxes provide a practical foundation for better resource tracking.</p><ul><li>Utility baseline for 3 centres</li><li>Material reuse practices recorded</li><li>Supplier returns for damaged stock</li></ul></article><article><div className="km-pillar-icon soc">S</div><h3>Social</h3><p>Education reach, teacher development and community collaboration are meaningful impact already present within the network.</p><ul><li>207 students in pilot sample</li><li>36 training hours recorded</li><li>Donation & collaboration evidence</li></ul></article><article><div className="km-pillar-icon gov">G</div><h3>Governance</h3><p>Existing operational manuals are a valuable starting point. The next opportunity is to add simple privacy, safeguarding and data ownership practices.</p><ul><li>Operating & teacher manuals exist</li><li>Centre reporting rhythm designed</li><li>Policy gaps clearly flagged</li></ul></article></div></section>
  <section className="km-report"><div><span>REPORT OUTPUT</span><h2>Kindle Mind ESG Starter<br />Baseline & Action Plan</h2><p>A clear, non-audit report designed to show what is already happening, what needs evidence, and which actions make sense next.</p><a className="dark-button" href="/contact">Discuss a founder-led pilot <b>→</b></a></div><div className="km-report-sheet"><div className="km-sheet-top"><b>ESG STARTER</b><span>PILOT CONFIGURATION</span></div><h3>Education Network<br />Baseline Report</h3><div className="km-sheet-stat"><b>3</b><span>pilot centres</span><b>207</b><span>students reached</span></div><div className="km-sheet-bars"><i><b style={{width:"70%"}} />Environment</i><i><b style={{width:"82%"}} />Social</i><i><b style={{width:"64%"}} />Governance</i></div><small>Planning view — final reports will use verified centre records.</small></div></section>
</main><SiteFooter /></>; }
