import Link from "next/link";
import { SiteNav, SiteFooter } from "../components/SiteNav";

export default function Impact() {
  return <><SiteNav/><main className="inner-page">
    <section className="impact-hero"><div className="impact-copy"><div className="v2-kicker">IMPACT DATA PILOT</div><h1>From field action<br/>to <em>evidence-backed impact.</em></h1><p>Our first real Impact Data Pilot turns Ocean Trash field records, waste categories and event photos into a traceable environmental activity record.</p><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Link className="v2-button primary" href="/impact/report">Open the data workspace <b>↗</b></Link><a className="v2-button ghost" href="/reports/beach-cleanup-impact-record.pdf" target="_blank" rel="noreferrer">View impact report <b>↗</b></a></div></div><div className="impact-collage"><img className="ic-main" src="/beach-team.jpeg" alt="Beach-cleaning volunteer team with collected waste"/><img className="ic-small" src="/beach-data.jpeg" alt="Volunteers completing field data forms"/><div className="ic-label"><span>VERIFIED FIELD EVIDENCE</span><b>Forms + categories + photos</b></div></div></section>
    <section className="impact-dashboard"><div className="id-head"><div><span>VERIFIED ACTIVITY RECORD</span><h2>Coastal clean-up overview</h2><p>Pantai Remis, Jeram, Selangor · 24 June 2026</p></div><em>Source report processed</em></div><div className="id-metrics"><div><span>Volunteers</span><b>35</b><small>adult volunteers</small></div><div><span>Cleanup hours</span><b>35</b><small>1-hour collection window</small></div><div><span>Items recorded</span><b>4,077</b><small>itemised field count</small></div><div><span>Waste weight</span><b>50.11<small> kg</small></b><small>23 bags collected</small></div></div><div className="impact-foot"><span>1 km cleaned</span><span>08:00–10:30 activity window</span><span>116.5 recorded items per volunteer</span></div><div className="id-content"><div className="id-bars"><div className="id-title"><b>Top waste categories</b><span>Counts from supplied field report</span></div><div className="id-bar"><span>Cigarette butts</span><i><b style={{width:"100%"}}/></i><em>1,443</em></div><div className="id-bar"><span>Straws / stirrers</span><i><b style={{width:"27%"}}/></i><em>389</em></div><div className="id-bar"><span>Plastic beverage bottles</span><i><b style={{width:"20%"}}/></i><em>288</em></div><div className="id-bar"><span>Plastic cups & plates</span><i><b style={{width:"20%"}}/></i><em>288</em></div><div className="id-bar"><span>Plastic bottle caps</span><i><b style={{width:"19%"}}/></i><em>280</em></div><p style={{margin:"22px 0 0",fontSize:12,color:"#577082",lineHeight:1.6}}><b style={{color:"#0a8278"}}>40.0% conservative plastic / foam share</b><br/>1,630 items were explicitly recorded as plastic or foam. Categories without a stated material are excluded from this calculation.</p></div><div className="id-evidence"><b>Evidence readiness</b><div><i>✓</i><span>Itemised Ocean Trash Data Report</span></div><div><i>✓</i><span>Volunteer field forms</span></div><div><i>✓</i><span>Event photographs</span></div><div><i>✓</i><span>Traceable impact record</span></div></div></div></section>
    <section className="impact-gallery"><div><div className="v2-kicker">THE DATA JOURNEY</div><h2>Every action leaves a record.</h2><p>ESG Starter keeps field evidence connected to the numbers, so an impact statement can be traced back to its source. The next version can add QR attendance, collection duration, before/after images, waste destination and GPS location.</p></div><img src="/beach-cleanup.jpeg" alt="Volunteers collecting coastal waste"/><img src="/volunteer-form.jpeg" alt="Ocean trash data form"/><img src="/trash-form.jpeg" alt="Completed trash category form"/></section>
  </main><SiteFooter/></>;
}
